'use client';

import { motion } from 'framer-motion';
import Image from 'next/image';
import type { PortfolioService } from '@/config/site';
import { siteConfig, whatsappLink } from '@/config/site';
import { EASE } from '@/components/ui/Reveal';

const container = { hidden: {}, visible: { transition: { staggerChildren: 0.1, delayChildren: 0.12 } } };
const reveal = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.65, ease: EASE } } };
const cardReveal = { hidden: { opacity: 0, y: 26 }, visible: { opacity: 1, y: 0, transition: { duration: 0.55, ease: EASE } } };

/** Vista editorial del portafolio, inspirada en el documento premium de impresión. */
export function Portfolio({ content, services }: { content: Record<string, string>; services: PortfolioService[] }) {
  return (
    <div className="min-w-0 overflow-x-hidden bg-paper-100 text-navy-900">
      <section className="relative overflow-hidden bg-navy-950 text-white">
        <div className="absolute inset-0 opacity-50 [background-image:linear-gradient(to_right,rgba(255,255,255,0.045)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,0.045)_1px,transparent_1px)] [background-size:72px_72px]" />
        <div className="pointer-events-none absolute -right-32 -top-40 h-[520px] w-[520px] rounded-full bg-gold-500/20 blur-3xl" />
        <motion.div className="relative mx-auto max-w-7xl px-4 pb-16 pt-28 sm:px-6 sm:pb-20 sm:pt-36 lg:px-8 lg:pt-44" initial="hidden" animate="visible" variants={container}>
          <motion.div variants={reveal} className="mb-10 flex min-w-0 items-center justify-between gap-4 border-b border-gold-500/60 pb-4 text-[10px] uppercase tracking-[0.14em] text-gold-300 sm:mb-12 sm:text-xs sm:tracking-[0.16em]"><span className="min-w-0 break-words font-mono">NeuroMundo S.A.S</span><span className="hidden shrink-0 text-right sm:inline">Portafolio de servicios · 2025</span></motion.div>
          <div className="grid items-center gap-10 lg:grid-cols-[minmax(0,1fr)_minmax(220px,0.48fr)] lg:gap-14">
            <motion.div variants={reveal} className="max-w-4xl"><p className="break-words font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-blue-300 sm:text-xs sm:tracking-[0.2em]">{siteConfig.slogan}</p><h1 className="mt-4 max-w-3xl break-words font-display text-4xl font-semibold leading-[1.08] tracking-tight sm:mt-5 sm:text-7xl">{content.portfolio_title ?? 'Portafolio de Servicios'}</h1><p className="mt-6 max-w-2xl break-words text-sm leading-relaxed text-slate-300 sm:mt-7 sm:text-lg">{content.portfolio_subtitle}</p><a href="#servicios" className="mt-8 inline-flex max-w-full items-center gap-3 rounded-none border border-gold-300 bg-gold-500 px-5 py-3 text-center text-[10px] font-bold uppercase tracking-[0.1em] text-navy-950 shadow-lg shadow-gold-500/20 transition-all hover:-translate-y-1 hover:bg-gold-400 sm:mt-9 sm:px-6 sm:text-xs sm:tracking-[0.12em]">Explorar servicios <span aria-hidden="true">↘</span></a></motion.div>
            <motion.div variants={reveal} className="flex justify-center lg:justify-end"><Image src="/logo.png" alt="Logotipo de NeuroMundo S.A.S" width={357} height={204} className="h-auto w-56 object-contain sm:w-72 lg:w-full lg:max-w-[320px]" /></motion.div>
          </div>
          <motion.div variants={reveal} className="mt-12 grid max-w-4xl grid-cols-2 border border-white/15 bg-white/[0.04] sm:mt-16 sm:grid-cols-4">{siteConfig.stats.map((stat, index) => <div key={stat.label} className={`min-w-0 px-3 py-4 sm:px-4 sm:py-5 ${index < 2 ? 'border-b' : ''} ${index % 2 === 0 ? 'border-r' : ''} border-white/10 sm:border-b-0 sm:border-r sm:last:border-r-0`}><p className="break-words font-mono text-xl font-semibold text-gold-300 sm:text-3xl">{stat.value}</p><p className="mt-2 break-words text-[9px] uppercase leading-snug tracking-wider text-slate-400 sm:text-[10px]">{stat.label}</p></div>)}</motion.div>
        </motion.div>
        <svg className="relative block h-12 w-full text-paper-50" viewBox="0 0 1440 64" fill="currentColor" preserveAspectRatio="none" aria-hidden="true"><path d="M0 64h1440V32C1080 64 720 0 0 32v32Z" /></svg>
      </section>

      <section id="servicios" className="bg-paper-50 px-4 py-16 sm:px-6 sm:py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><motion.div variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-80px' }} className="mb-12 max-w-3xl sm:mb-16"><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-blue-500 sm:text-xs sm:tracking-[0.18em]">01 · Soluciones integrales</p><h2 className="mt-4 break-words font-display text-3xl font-semibold leading-tight text-navy-950 sm:text-5xl">Un solo interlocutor para la operación de tu IPS</h2><p className="mt-5 max-w-2xl text-sm leading-relaxed text-slate-600 sm:text-base">Cada línea puede contratarse de forma independiente o integrada, con soluciones diseñadas para instituciones de salud en Colombia.</p></motion.div>
        <div className="space-y-8">{services.map((service) => <motion.article id={service.id} key={service.id} variants={cardReveal} initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-70px' }} whileHover={{ y: -4 }} className="scroll-mt-24 grid min-w-0 gap-6 border-t border-paper-300 pt-7 sm:gap-8 sm:pt-8 md:grid-cols-[minmax(260px,0.82fr)_1.5fr] lg:gap-16 lg:pt-10"><div className="min-w-0"><div className="flex items-start justify-between gap-3"><span className="shrink-0 font-mono text-4xl font-semibold leading-none text-gold-500/70 sm:text-5xl">{service.num}</span><span className="max-w-[65%] break-words text-right rounded-none border border-navy-200 bg-navy-50 px-2 py-1 font-mono text-[9px] uppercase leading-snug tracking-wider text-navy-600 sm:px-3 sm:text-[10px]">{service.category}</span></div><h3 className="mt-6 break-words font-display text-xl font-semibold leading-snug text-navy-950 sm:mt-7 sm:text-2xl">{service.title}</h3><p className="mt-4 break-words text-sm leading-relaxed text-slate-600">{service.description}</p></div><div className="relative min-w-0 border border-paper-300 bg-white p-5 shadow-card sm:p-9"><div className="absolute left-0 top-0 h-full w-1 bg-gold-500" /><p className="mb-5 flex items-center gap-3 font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-navy-700 sm:text-[11px] sm:tracking-[0.16em]"><span className="h-px w-7 shrink-0 bg-gold-500" /> Incluye</p><ul className="grid gap-4 text-sm leading-relaxed text-slate-600 sm:grid-cols-2">{service.details.map((detail) => <li key={detail} className="flex min-w-0 gap-3"><span className="mt-1 shrink-0 text-gold-500">◆</span><span className="break-words">{detail}</span></li>)}</ul></div></motion.article>)}</div>
      </div></section>

      <section className="relative overflow-hidden bg-gradient-to-br from-navy-950 to-navy-700 px-4 py-16 text-center text-white sm:px-6 sm:py-20 lg:py-24"><div className="pointer-events-none absolute right-[-8%] top-[-55%] h-[500px] w-[500px] rounded-full border border-gold-500/20" /><div className="relative mx-auto max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-gold-300 sm:text-xs sm:tracking-[0.18em]">02 · Hablemos</p><h2 className="mt-4 break-words font-display text-3xl font-semibold sm:text-5xl">¿Necesitas una propuesta a la medida?</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-relaxed text-slate-300 sm:text-base">Cuéntanos el reto de tu institución y diseñemos juntos una solución clara, oportuna y sostenible.</p><a href={whatsappLink('Hola NeuroMundo S.A.S 👋 Quisiera información sobre el portafolio de servicios.')} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex max-w-full rounded-none bg-gold-500 px-5 py-3.5 text-center text-[10px] font-bold uppercase tracking-[0.1em] text-navy-950 transition-all hover:-translate-y-1 hover:bg-gold-400 sm:px-7 sm:text-xs sm:tracking-[0.12em]">Contactar por WhatsApp</a></div></section>
    </div>
  );
}